
spring:
    application:
        name: cerebro
    datasource:
        password: gris
        url: jdbc:h2:~/cerebroGris
        username: 
                
                
logging:  
  pattern:
    console: '%logger{36} - %msg%n'
  level:
    root: INFO    